### ISSUE TITLE
当我导入项目后maven import的时候会提示 Cannot resolve com.amdelamar:jhash:2.1.2

### ISSUE THREAD

**Issue by AtomRun** [TaleLin/lin-cms-spring-boot#123]
**描述 bug**

**经查看，这个无法导入的jar是在`lin-cms-core-0.11-RC3.pom`中定义的，但是我使用阿里云或者maven官方的源都找不到该jar**
```java
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/amdelamar/jhash/exception/InvalidHashException
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
```
**出现该问题的最顶端在`UserIdentityServiceImpl`类中49行的`verify`方法中**
- 你是如何操作的？
**下载`sleeve0.2.0`版本后import库然后run**
- 发生了什么？

- 你觉得应该出现什么？

**你使用哪个版本出现该问题？**
`sleeve0.2.0`
如果使用`master`，请表明是 master 分支，否则给出具体的版本号

**如何再现**

If your bug is deterministic, can you give a minimal reproducing code?
Some bugs are not deterministic. Can you describe with precision in which context it happened?
If this is possible, can you share your code?

如果你确定存在这个 bug，你能提供我们一个最小的实现代码吗？
一些 bug 是不确定，只会在某些条件下触发，你能详细描述一下具体的情况和提供复现的步骤吗？
当然如果你提供在线的 repo，那就再好不过了。

如果你发现了 bug，并修复了它，请用`git rebase`合并成一条标准的`fix: description`提交，然后向我们的
项目提 PR，我们会在第一时间审核，并感谢您的参与。

**Comment by AtomRun** [comment]
## 问题解决
去[mavenRepository](https://mvnrepository.com/artifact/com.amdelamar/jhash/2.1.2)按照路径下载jar放到自己的repo中就可以了
